velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    stamp_smoothed_velocity_with_smoothing_time: False
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.8, 0.0, 1.8]
    min_velocity: [0.0, 0.0, -1.8]
    max_accel: [1.0, 0.0, 3.0]
    max_decel: [-1.0, 0.0, -3.0]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

